### PR TITLE
Fix address issue

### PR DESCRIPTION
**Pull request by GrenderG**
Mentioned in #2.

### CODE REVIEW

**Comment by GrenderG** [comment]
I have noticed there are more issues with offsets, at least regarding the ones from MemoryCard.txt, @PeterLemon.

**Comment by PeterLemon** [comment]
Hi I do not have the same problems as you, no idea where that typo came from as it is not in my src, Plenty of people have used my patch correctly, so I am closing this pull request as I would not be able to use my obviously different game iso to make changes.

**Comment by GrenderG** [comment]
> Hi I do not have the same problems as you, no idea where that typo came from as it is not in my src, Plenty of people have used my patch correctly, so I am closing this pull request as I would not be able to use my obviously different game iso to make changes.

Can you share the hash of your ISO? Has it been ripped from the original disk?

**Comment by PeterLemon** [comment]
Hi, I did rip it myself, but it does seem after verifying the integrity of the ISO using dolphin right click properties/verify on the game it comes up as a bad dump :(
Here is the hashes of my Homeland ISO file anyway:
CRC32: a23fd673
MD5: 2afbdd672386f286161fe426c40dc4e1
SHA-1: 7f202d3b3a9e9b2d46815cb1f8b5558df7304f25

I do not know what to do really, as I my GC discs are stored somewhere else atm.
Would be ace if you could verify your dump to make sure it does not say "bad dump" in dolphin too, so at least we know yours is correct.
Probably was a fluke other people were able to use my translation patches correctly.

**Comment by GrenderG** [comment]
I'm sorry to hear that! I verified my dump and it's a valid one, yup. Let me know if you want a copy of it, although you can find it online if you search for this sha1: `5e74644701364263bdd016d2d54d25dee1436345`.

P.S.: I dumped mine with a Wii + CleanRip, how did you dump yours?

**Pull request closed without merging**
